# Numpy(Numeric python)


In [3]:
import numpy as np 

#  Numpy的数组对象及其索引
## 假如我们想将列表中的每个元素增加1，但列表不支持这样的操作：


In [4]:
a=[1,2,3,4]

b=[2,3,4,5]

In [5]:
a+b

[1, 2, 3, 4, 2, 3, 4, 5]

In [6]:
[x+y for x,y in zip(a,b)]

[3, 5, 7, 9]

In [7]:
c=np.array([1,2,3,4])

In [8]:
c+1

array([2, 3, 4, 5])

### 产生数组

In [9]:
l=[1,2,3,4]
a=np.array(l)

In [10]:
print(a)

[1 2 3 4]


### 生成全零数组(默认给到的都是浮点数

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 生成全一数组

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

### 可以使用fill方法将数组设定为指定值

In [14]:
a=np.array([1,2,3,4])

In [15]:
a.fill(5)

In [16]:
print(a)

[5 5 5 5]


### 数组中要求所有元素的dtype是一样的，如果传入参数的类型和数组的类型不一样，需要按照已有的类型进行转换  

In [17]:
a.fill(2.5)
a

array([2, 2, 2, 2])

In [18]:
a=a.astype('float')
a.fill(2.5)
a

array([2.5, 2.5, 2.5, 2.5])

###  生成整数数列

In [19]:
b=np.arange(1,10) #生成整数序列 
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 生成等差数列 

In [20]:
a=np.linspace(1,10,5) #起始，结束，个数

In [21]:
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### 生成随机数

In [22]:
np.random.rand(5)

array([0.75140702, 0.51186527, 0.20956201, 0.9429963 , 0.68174429])

In [23]:
np.random.randn(5)#符合正态分布（normal distribution）

array([-0.13248223,  1.07205539, -0.48715349,  0.36419161, -0.25438067])

In [111]:
np.random.randint(1,10,5) #生成整数

array([6, 9, 4, 6, 9])

In [25]:
type(a)

numpy.ndarray

### 查看数组中的数据类型 

In [26]:
a.dtype

dtype('float64')

### 查看形状，会返回一个元祖，每个元素代表这一维的元素数目 

In [27]:
a.shape

(5,)

In [28]:
b.shape

(9,)

In [29]:
b.ndim

1

In [30]:
a.size

5

### 查看数组的维度

In [31]:
a.ndim

1

## 索引和切片 

In [32]:
a=np.array([0,1,2])
a

array([0, 1, 2])

In [33]:
a[0]

0

In [34]:
a[-1] #负索引

2

### 修改第一个元素的值 

In [35]:
a[0]=10
a

array([10,  1,  2])

### 假如我们记录一部电影的累计票房

In [36]:
ob=np.array([21000,21800,22240,23450,25000])
ob

array([21000, 21800, 22240, 23450, 25000])

### 可以这样计算票房 

In [37]:
x=ob[0:-1]
y=ob[1:]
x,y

(array([21000, 21800, 22240, 23450]), array([21800, 22240, 23450, 25000]))

In [38]:
y-x

array([ 800,  440, 1210, 1550])

### 生成多维数组,实际上我们传入的是以一个列表，在列表中有一个二维数组

In [39]:
c=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
c

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

### 查看矩阵（数组）维度和每个维度的个数 

In [40]:
c.shape #和一维数组不一样  ，c.shape 表示 3行 5列

(3, 5)

### 查看数组的个数

In [41]:
c.size

15

### 查看数组的维数

In [42]:
c.ndim

2

###   对于二维数组，可以传入2个数字来索引

In [43]:
d=np.array([[0,1,2,3],[10,11,12,13]])
d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [44]:
d[1,3]

13

### 其中，1是行索引，3是列索引，中间用逗号隔开，事实上，python会将它们看成一个元组（1，3），按照顺序进行对应,可以利用索引给它赋值

In [45]:
d[1,3]=-1
d

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

### 我们还可以使用单个索引来索引一整行类容

In [46]:
d[1]

array([10, 11, 12, -1])

### python会将这个单个元组当成第一堆索引，然后返回对应的内容

In [47]:
d[0:,1]

array([ 1, 11])

In [48]:
d[:,1]

array([ 1, 11])

### 多维数组切片
### 多维数组，也支持切片操作

In [49]:
f=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
f

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

### 得到第一行第4个和第5个两个元素

In [50]:
f[0,3:5]

array([3, 4])

### 得到最后两行的最后两列

In [51]:
f[4:6,4:]

array([[44, 45],
       [54, 55]])

### 每一维都支持切片的规则，包括负索引[lower:upper:step]
### 例如，取出第3，5的奇数列

In [52]:
f[2::2,2::2]

array([[22, 24],
       [42, 44]])

### 切片是引用

In [53]:
a=np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [54]:
b=a[2:4]
b

array([2, 3])

In [55]:
b[0]=10
a

array([ 0,  1, 10,  3,  4])

### 引用机制意味着python并没有为b分配新的空间来储存它的值，而是b指向了a所分配的内存空间，因此b改变，a会改变a的值
### 但是在列表中并不会出现这种现象

In [56]:
a=[1,2,3,4,5]
b=a[0:2]
print(b)
print(id(a),id(b))

[1, 2]
102155016 107080072


In [57]:
b[0]=10
print(a)

[1, 2, 3, 4, 5]


### 可以使用copy（）方法产生一个复制，这个复制会申请新的内存 

In [58]:
a=np.array([0,1,2,3,4])
b=a[2:4].copy()
b[0]=10
a

array([0, 1, 2, 3, 4])

# 花式索引
### 切片只能支持连续或者等间隔的切片操作，要想实现任意位置的操作，需要使用花式索引fancy slicing

### 一维花式索引

### 与range函数类似，我们可以使用arange函数产生等差数组

In [59]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### 花式索引需要指定索引位置

In [60]:
index=[1,2,-3]
y=a[index]
y

array([10, 20, 70])

### 还可以使用布尔数进行花式索引,但是布尔数组必须和数组的个数一致

In [61]:
mask=np.array([0,1,1,0,0,1,0,0,0,0],dtype=bool)
mask

array([False,  True,  True, False, False,  True, False, False, False,
       False])

In [62]:
a[mask]

array([10, 20, 50])

### 二维花式索引

### 对于二维花式索引，我们需要给定行和列的值

In [63]:
f=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
f

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

### 返回的是一条次对角线山的5个值 

In [64]:
f[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

### 返回的是最后三行的第1，3，5列

In [65]:
f[3:,[0,2,4]]

array([[30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

 ### 也可以使用mask进行索引
 

In [66]:
mask=np.array([1,0,1,0,0,1],dtype=bool)

In [67]:
f[mask,2]

array([ 2, 22, 52])

### 花式索引是一个复制新的储存位置，而不是指向原位置

### 不完全索引 

In [68]:
f[:3]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

### 使用花式索引取出2，3，5行

In [69]:
con=np.array([0,1,1,0,1,0],dtype=bool)

In [70]:
f[con,]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

# where语句
 where(array)
 where函数会返回非零元素索引

### 一维数组

In [71]:
a=np.array([0,12,5,20])

### 判断数组中的元素是不是都大于0

In [72]:
a>10

array([False,  True, False,  True])

### 数组中所有大于10的元素位置：where的返回值是一个元组，返回的是索引位置，索引[1,3]

In [73]:
np.where(a>10)

(array([1, 3], dtype=int64),)

### 也可以直接用数组操作

In [74]:
a[a>10]

array([12, 20])

In [75]:
a[np.where(a>10)]

array([12, 20])

### 类型转换

In [76]:
a=np.array([1,5,3],dtype=float)
a

array([1., 5., 3.])

### asarray函数

In [77]:
a=np.array([1,2,3])
np.asarray(a,dtype=float)

array([1., 2., 3.])

### astype方法:
astype返回一个新的数组

In [78]:
a.astype(float)

array([1., 2., 3.])

In [79]:
a

array([1, 2, 3])

In [80]:
b=a.astype(float)
b

array([1., 2., 3.])

In [81]:
b[0]=0.5
b

array([0.5, 2. , 3. ])

# 数组操作
### 以豆瓣10部高分电影电影为例

In [82]:
mv_name=np.array(['肖生克的救赎','控方证人','美丽人生','阿甘正传','霸王别姬','泰坦尼克号','辛德勒的名单','这个杀手不太冷','疯狂动物城','海豚湾'])
mv_name

array(['肖生克的救赎', '控方证人', '美丽人生', '阿甘正传', '霸王别姬', '泰坦尼克号', '辛德勒的名单',
       '这个杀手不太冷', '疯狂动物城', '海豚湾'], dtype='<U7')

In [83]:
## 评分人数
mv_num=np.array([692795,42995,327855,580897,478523,147074,306904,662552,284652,159032])
mv_num

array([692795,  42995, 327855, 580897, 478523, 147074, 306904, 662552,
       284652, 159032])

In [84]:
## 评分
mv_score=np.array([9.6,9.5,9.5,9.4,9.4,9.4,9.4,9.3,9.3,9.3])
mv_score

array([9.6, 9.5, 9.5, 9.4, 9.4, 9.4, 9.4, 9.3, 9.3, 9.3])

In [85]:
mv_score.size

10

In [86]:
## 电影时长
mv_length=np.array([142,116,116,142,171,194,195,133,109,92])
mv_length

array([142, 116, 116, 142, 171, 194, 195, 133, 109,  92])

### 数组排序
#### sort函数

In [87]:
np.sort(mv_num)

array([ 42995, 147074, 159032, 284652, 306904, 327855, 478523, 580897,
       662552, 692795])

#### argsort函数

In [88]:
order=np.argsort(mv_num)
order

array([1, 5, 9, 8, 6, 2, 4, 3, 7, 0], dtype=int64)

In [89]:
mv_name[order]

array(['控方证人', '泰坦尼克号', '海豚湾', '疯狂动物城', '辛德勒的名单', '美丽人生', '霸王别姬', '阿甘正传',
       '这个杀手不太冷', '肖生克的救赎'], dtype='<U7')

####  求和

In [90]:
np.sum(mv_num)

3683279

In [91]:
mv_num.sum()

3683279

#### 最大值，最小值，均值，标准差

In [92]:
np.max(mv_length)

195

In [93]:
np.min(mv_score)

9.3

In [94]:
np.mean(mv_length)

141.0

In [95]:
np.std(mv_length)

33.713498780162226

###  相关系数矩阵

In [96]:
np.cov(mv_score,mv_length)

array([[9.88888889e-03, 4.55555556e-01],
       [4.55555556e-01, 1.26288889e+03]])

### 多维数组的操作

In [97]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [98]:
a.shape=2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
a.shape

(2, 3)

### 数组形状，与之对应的的方法是reshape，但它不会修改原来数组的值，而是返回一个新的数组 

In [100]:
b=a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

### 转置

In [101]:
b.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [102]:
b.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

### 数组连接
### 有时我们需要将不同数组按照一定的顺序连接起来：
#### concatenate((a0,a1....aN)),axis=0) 如果需要纵向连接则改成axis=1
### 注意，这些数组要用（）包括到一个元组中去，除了给定的轴外，这些数组其他轴的长度必须一样的。

In [103]:
x=np.array([[0,1,2],[10,11,12]])
y=np.array([[50,51,52],[60,61,62]])
print(x,y,x.shape,y.shape,sep='\n')
x.ndim

[[ 0  1  2]
 [10 11 12]]
[[50 51 52]
 [60 61 62]]
(2, 3)
(2, 3)


2

In [104]:
z=np.concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [136]:
h=np.concatenate((x,y),axis=1)
h

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

### 这里x和y的形状是一样的， 还可以将它们连接成三位数组，但是concatenate没有这样的功能,但是可以这样做

In [106]:
z=np.array((x,y))
print(z)
z.ndim

[[[ 0  1  2]
  [10 11 12]]

 [[50 51 52]
  [60 61 62]]]


3

### 可以用下面三种函数来进行连接:
 * vstack
 * hstack
 * dstack


In [107]:
np.vstack((x,y))

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [108]:
np.hstack((x,y))

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [109]:
np.dstack((x,y))

array([[[ 0, 50],
        [ 1, 51],
        [ 2, 52]],

       [[10, 60],
        [11, 61],
        [12, 62]]])

In [110]:
c=np.arange(11)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
a=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
a.shape

(4, 3)

In [133]:
a.ndim

2

In [134]:
a[1:,1:]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [128]:
np.insert(a,1,[[1],[2],[3]],axis=1)

array([[1, 1, 2, 3, 2],
       [3, 1, 2, 3, 4],
       [5, 1, 2, 3, 6]])