# 第二次课作业

In [29]:
import numpy as np

（1）创建一个1到10的数组，然后逆序输出。

In [137]:
a=np.arange(11)
print(a)
order=reversed(np.argsort(a))
a[list(order)]

[ 0  1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [135]:
Z = np.arange(50)
Z = Z[::-1]
print (Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。


In [31]:
b=np.ones((4,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
b.T

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)


In [33]:
b=np.random.random((3,3,3))
b

array([[[0.39912783, 0.70482811, 0.29237632],
        [0.29499963, 0.14685063, 0.47907436],
        [0.76396381, 0.74561833, 0.66094501]],

       [[0.76732422, 0.13468616, 0.96204517],
        [0.0804695 , 0.97724159, 0.38047133],
        [0.05463387, 0.34662924, 0.12534288]],

       [[0.54289255, 0.1201013 , 0.08488192],
        [0.18693657, 0.36266421, 0.07113655],
        [0.92224792, 0.18470094, 0.56278228]]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [53]:
a=np.random.randint(1,10,10)
print(np.sort(a),np.max(a),np.min(a))

[3 3 3 5 6 6 7 7 7 8] 8 3


（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [60]:
b=np.random.random_integers(1,10,10)
b[(b%2==1)]

F:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  """Entry point for launching an IPython kernel.


array([9, 9, 9, 5, 5, 9, 5])

（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [62]:
c=np.linspace(1,100,5)
c=c.astype('int')
c

array([  1,  25,  50,  75, 100])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [80]:
d=np.random.randint(1,10,10)
e=-d[(d>3)&(d<8)]
e

array([-4, -6])

（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [91]:
a=np.array([1, 2, 3, 4, 5])
a=a.reshape(5,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [93]:
a=np.insert(a,1,0,axis=1)
a.flatten()

array([1, 0, 2, 0, 3, 0, 4, 0, 5, 0])

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。


In [103]:
a=np.random.randint(10,100,25)
a=a.reshape(5,5)
a


array([[72, 68, 32, 93, 73],
       [51, 12, 57, 44, 21],
       [79, 18, 16, 33, 56],
       [56, 86, 80, 96, 49],
       [86, 75, 17, 20, 62]])

In [104]:
a[[1,2], :] = a[[2,1], :]
a

array([[72, 68, 32, 93, 73],
       [79, 18, 16, 33, 56],
       [51, 12, 57, 44, 21],
       [56, 86, 80, 96, 49],
       [86, 75, 17, 20, 62]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

（12）创建一个长度为10的随机向量，并求其累计和。

（13）将数组中的所有奇数替换成-1。

In [129]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
a[(a%2==1)]=-1
a

array([-1,  2, -1,  2, -1,  4, -1,  4, -1,  6])

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [118]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
index=np.where(a==b)
index


(array([1, 3, 5, 7], dtype=int64),)

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])